name: Deploy to telegram

on:
  workflow_dispatch: # allow jobs manual run
  release:
    types: [published]

jobs:
  send-to-telegram:
    name: send file to telegram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: make gradle executable
        run: chmod +x ./android/gradlew

      - name: generate apk
        run: |
          cd android
          ./gradlew assembleRelease
      - name: artifacts apk
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload to Telegram Bot
        run: |
          cd android/app/build/outputs/apk/release/
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F text='App Released!' ${{secrets.TG_BOT_TOKEN}}/sendMessage
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=@app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument
